<a href="https://colab.research.google.com/github/DineshChauhan/Deep-Tutorials-for-PyTorch/blob/master/Building_a_Neural_Network_from_Scratch_in_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import torch 

In [0]:
#input Tensor
x = torch.Tensor([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
#Output
y = torch.Tensor(([1],[1],[0]))

In [125]:
x.shape,y.shape

(torch.Size([3, 4]), torch.Size([3, 1]))

In [0]:
#Sigmoid Function
def sigmoid(x):
  return 1/(1+torch.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x):
  return x*(1-x)

In [0]:
#define number of times model will run & Learning rate etc.
epoch = 7000
lr =0.1
inputlayer_neurons = x.shape[1]
hiddenlayer_neurons = 3
output_neurons =1

In [135]:
print(inputlayer_neurons),print(hiddenlayer_neurons)

4
3


(None, None)

In [0]:
#Intialise Weight & Biases with random numbers
wh = torch.randn(inputlayer_neurons,hiddenlayer_neurons).type(torch.FloatTensor)
bh = torch.randn(1,hiddenlayer_neurons).type(torch.FloatTensor)
wout= torch.rand(hiddenlayer_neurons,output_neurons)
bout=torch.randn(1,output_neurons)

In [137]:
print(wh),print(bh),print(wout),print(bout)

tensor([[ 0.1344,  0.3270, -0.7251],
        [ 0.9491,  0.8158,  1.2328],
        [-0.4021,  2.2354, -0.6518],
        [ 0.2390,  1.1505, -0.7792]])
tensor([[ 0.1173, -0.9270,  2.0356]])
tensor([[0.1446],
        [0.7816],
        [0.6959]])
tensor([[-1.2702]])


(None, None, None, None)

In [0]:
for i in range(epoch):
  #Forward Propogation
  #multiply input matrix with weights
  hidden_layer_input1 = torch.mm(x,wh)
  #Now add biases to output matrix
  hidden_layer_input = hidden_layer_input1 + bh
  # Apply activation function
  hidden_layer_activation = sigmoid(hidden_layer_input)

   #output layer is then multiplid with weights & biase is added
  output_layer_input1 = torch.mm(hidden_layer_activation,wout)
  output_layer_input = output_layer_input1 + bout
  output = sigmoid(output_layer_input)
  
  #Backpropogation

  E = y - output # this is your error
  slope_output_layer = derivatives_sigmoid(output)
  slope_hidden_layer = derivatives_sigmoid(hidden_layer_activation)

  d_output = E * slope_output_layer

  Error_at_hidden_layer = torch.mm(d_output,wout.t())
  d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer

  #update weights & Biases 
  wout += torch.mm(hidden_layer_activation.t(),d_output) * lr
  bout += d_output.sum() * lr

  wh += torch.mm(x.t(),d_hiddenlayer) * lr
  bh += d_output.sum() * lr

In [139]:
print('actual  :\n',y,'\n')
print('predicted :\n',output)

actual  :
 tensor([[1.],
        [1.],
        [0.]]) 

predicted :
 tensor([[0.9800],
        [0.9767],
        [0.0307]])


# Solving an Image Classification Problem using PyTorch